import { db } from "./index";
import { triviaQuestions, triviaResponses } from "./schema";

const questions = [
  // ── EASY (5) — well-known draft facts ───────────────────────────────────────
  {
    question: "Who was the #1 overall pick in the 2024 NFL Draft?",
    optionA: "Caleb Williams",
    optionB: "Jayden Daniels",
    optionC: "Drake Maye",
    optionD: "Marvin Harrison Jr.",
    correctOption: "a",
    category: "draft_history",
    difficulty: "easy",
  },
  {
    question: "Which player was selected #1 overall in the 2023 NFL Draft?",
    optionA: "C.J. Stroud",
    optionB: "Bryce Young",
    optionC: "Anthony Richardson",
    optionD: "Will Anderson Jr.",
    correctOption: "b",
    category: "draft_history",
    difficulty: "easy",
  },
  {
    question: "Which team held the #1 overall pick in the 2021 NFL Draft and selected Trevor Lawrence?",
    optionA: "New York Jets",
    optionB: "Jacksonville Jaguars",
    optionC: "Cincinnati Bengals",
    optionD: "Atlanta Falcons",
    correctOption: "b",
    category: "draft_history",
    difficulty: "easy",
  },
  {
    question: "How many rounds are in the modern NFL Draft?",
    optionA: "5",
    optionB: "6",
    optionC: "7",
    optionD: "8",
    correctOption: "c",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the standard distance of the 40-yard dash measured at the NFL Combine?",
    optionA: "36 yards",
    optionB: "40 yards",
    optionC: "44 yards",
    optionD: "50 yards",
    correctOption: "b",
    category: "combine",
    difficulty: "easy",
  },

  // ── MEDIUM (5) — requires some draft knowledge ───────────────────────────────
  {
    question: "Tom Brady was selected in which round of the 2000 NFL Draft?",
    optionA: "4th round",
    optionB: "5th round",
    optionC: "6th round",
    optionD: "7th round",
    correctOption: "c",
    category: "draft_history",
    difficulty: "medium",
  },
  {
    question: "Patrick Mahomes was drafted by the Kansas City Chiefs in the 2017 NFL Draft with which pick number?",
    optionA: "7th overall",
    optionB: "10th overall",
    optionC: "14th overall",
    optionD: "20th overall",
    correctOption: "b",
    category: "draft_history",
    difficulty: "medium",
  },
  {
    question: "In 2016, the Los Angeles Rams traded up to #1 overall to draft Jared Goff, giving up multiple picks to which team?",
    optionA: "Cleveland Browns",
    optionB: "Tennessee Titans",
    optionC: "San Francisco 49ers",
    optionD: "Philadelphia Eagles",
    correctOption: "b",
    category: "trades",
    difficulty: "medium",
  },
  {
    question: "How many minutes does each team in the first round have to submit their pick at the NFL Draft?",
    optionA: "5 minutes",
    optionB: "10 minutes",
    optionC: "15 minutes",
    optionD: "20 minutes",
    correctOption: "b",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "At the 2024 NFL Combine, which receiver ran a 4.21 40-yard dash, setting a new combine record?",
    optionA: "Malik Nabers",
    optionB: "Brian Thomas Jr.",
    optionC: "Xavier Worthy",
    optionD: "Marvin Harrison Jr.",
    correctOption: "c",
    category: "combine",
    difficulty: "medium",
  },

  // ── HARD (5) — deep draft trivia ─────────────────────────────────────────────
  {
    question: "Bo Jackson was famously drafted first overall in 1986 by which team, but refused to play for them?",
    optionA: "Houston Oilers",
    optionB: "Dallas Cowboys",
    optionC: "Tampa Bay Buccaneers",
    optionD: "Los Angeles Rams",
    correctOption: "c",
    category: "draft_history",
    difficulty: "hard",
  },
  {
    question: "In what year was the first NFL Draft held?",
    optionA: "1930",
    optionB: "1936",
    optionC: "1941",
    optionD: "1945",
    correctOption: "b",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "In 2021, the San Francisco 49ers traded three first-round picks to move up to #3 overall to eventually select Trey Lance. Which team traded down?",
    optionA: "Atlanta Falcons",
    optionB: "Jacksonville Jaguars",
    optionC: "Miami Dolphins",
    optionD: "New York Jets",
    correctOption: "a",
    category: "trades",
    difficulty: "hard",
  },
  {
    question: "Which team famously traded away multiple first-round picks in 1999 — including picks the Cleveland Browns used to re-enter the league — in exchange for the right to select Ricky Williams?",
    optionA: "Washington Redskins",
    optionB: "Dallas Cowboys",
    optionC: "New Orleans Saints",
    optionD: "Minnesota Vikings",
    correctOption: "c",
    category: "trades",
    difficulty: "hard",
  },
  {
    question: "John Ross set the NFL Combine 40-yard dash record in 2017 with a time of 4.22 seconds. Which position did he play?",
    optionA: "Running Back",
    optionB: "Cornerback",
    optionC: "Wide Receiver",
    optionD: "Safety",
    correctOption: "c",
    category: "combine",
    difficulty: "hard",
  },

  // ── BATCH 2: EASY (10 more) ─────────────────────────────────────────────────
  {
    question: "Which position does the NFL Combine's bench press test measure (225 lbs)?",
    optionA: "Upper body strength",
    optionB: "Lower body strength",
    optionC: "Cardio endurance",
    optionD: "Flexibility",
    correctOption: "a",
    category: "combine",
    difficulty: "easy",
  },
  {
    question: "What city has hosted the NFL Draft most often?",
    optionA: "Las Vegas",
    optionB: "Chicago",
    optionC: "New York",
    optionD: "Nashville",
    correctOption: "c",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Peyton Manning was the #1 overall pick in which year?",
    optionA: "1997",
    optionB: "1998",
    optionC: "1999",
    optionD: "2000",
    correctOption: "b",
    category: "draft_history",
    difficulty: "easy",
  },
  {
    question: "Which team drafted Lamar Jackson in 2018?",
    optionA: "Buffalo Bills",
    optionB: "Baltimore Ravens",
    optionC: "Cleveland Browns",
    optionD: "New York Jets",
    correctOption: "b",
    category: "draft_history",
    difficulty: "easy",
  },
  {
    question: "The NFL Combine is held annually in which city?",
    optionA: "Dallas",
    optionB: "New York",
    optionC: "Indianapolis",
    optionD: "Los Angeles",
    correctOption: "c",
    category: "combine",
    difficulty: "easy",
  },
  {
    question: "How many teams are in the NFL?",
    optionA: "30",
    optionB: "32",
    optionC: "34",
    optionD: "36",
    correctOption: "b",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which QB was drafted #1 overall in 2020 by the Cincinnati Bengals?",
    optionA: "Tua Tagovailoa",
    optionB: "Justin Herbert",
    optionC: "Joe Burrow",
    optionD: "Jordan Love",
    correctOption: "c",
    category: "draft_history",
    difficulty: "easy",
  },
  {
    question: "The vertical jump at the NFL Combine measures what?",
    optionA: "How high a player can reach from a standing position",
    optionB: "How far a player can jump forward",
    optionC: "How quickly a player can climb a wall",
    optionD: "How many jumps in 30 seconds",
    correctOption: "a",
    category: "combine",
    difficulty: "easy",
  },
  {
    question: "Which team has the most #1 overall draft picks in NFL history?",
    optionA: "Cleveland Browns",
    optionB: "Indianapolis Colts",
    optionC: "Tampa Bay Buccaneers",
    optionD: "Detroit Lions",
    correctOption: "a",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Andrew Luck was drafted #1 overall in 2012 by which team?",
    optionA: "Washington Commanders",
    optionB: "Indianapolis Colts",
    optionC: "Cleveland Browns",
    optionD: "St. Louis Rams",
    correctOption: "b",
    category: "draft_history",
    difficulty: "easy",
  },

  // ── BATCH 2: MEDIUM (12 more) ──────────────────────────────────────────────
  {
    question: "Which player was selected first overall by the Houston Texans in the 2014 NFL Draft?",
    optionA: "Johnny Manziel",
    optionB: "Jadeveon Clowney",
    optionC: "Blake Bortles",
    optionD: "Khalil Mack",
    correctOption: "b",
    category: "draft_history",
    difficulty: "medium",
  },
  {
    question: "In 2018, the Cleveland Browns had two top-4 picks. Who did they select at #1 and #4?",
    optionA: "Baker Mayfield and Denzel Ward",
    optionB: "Sam Darnold and Bradley Chubb",
    optionC: "Josh Allen and Roquan Smith",
    optionD: "Baker Mayfield and Saquon Barkley",
    correctOption: "a",
    category: "draft_history",
    difficulty: "medium",
  },
  {
    question: "What is the 3-cone drill at the NFL Combine designed to measure?",
    optionA: "Straight-line speed",
    optionB: "Agility and change of direction",
    optionC: "Endurance",
    optionD: "Reaction time",
    correctOption: "b",
    category: "combine",
    difficulty: "medium",
  },
  {
    question: "Which team traded the farm to move up and draft RG3 (Robert Griffin III) in 2012?",
    optionA: "Washington Redskins",
    optionB: "Cleveland Browns",
    optionC: "Minnesota Vikings",
    optionD: "Jacksonville Jaguars",
    correctOption: "a",
    category: "trades",
    difficulty: "medium",
  },
  {
    question: "Aaron Rodgers famously fell in the 2005 NFL Draft. How many picks waited before he was selected?",
    optionA: "15",
    optionB: "20",
    optionC: "24",
    optionD: "28",
    correctOption: "c",
    category: "draft_history",
    difficulty: "medium",
  },
  {
    question: "Which conference is the AFC West division part of?",
    optionA: "NFC",
    optionB: "AFC",
    optionC: "Both",
    optionD: "Neither",
    correctOption: "b",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "In the 2017 NFL Draft, the Chicago Bears traded up one spot to #2 to draft which player?",
    optionA: "Deshaun Watson",
    optionB: "Patrick Mahomes",
    optionC: "Mitchell Trubisky",
    optionD: "Solomon Thomas",
    correctOption: "c",
    category: "trades",
    difficulty: "medium",
  },
  {
    question: "What does 'compensatory pick' mean in the NFL Draft?",
    optionA: "A pick given to teams that lost key free agents",
    optionB: "A pick that compensates for a bad trade",
    optionC: "An extra pick for winning the Super Bowl",
    optionD: "A pick traded between divisions",
    correctOption: "a",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "DK Metcalf's legendary NFL Combine performance in 2019 included a 4.33 forty. What was notable about his bench press?",
    optionA: "He set the WR record with 33 reps",
    optionB: "He only managed 11 reps but his speed overshadowed it",
    optionC: "He refused to do the bench press",
    optionD: "He did 27 reps, highest for a WR that year",
    correctOption: "d",
    category: "combine",
    difficulty: "medium",
  },
  {
    question: "Which team drafted Russell Wilson in the 3rd round of the 2012 NFL Draft?",
    optionA: "Denver Broncos",
    optionB: "Seattle Seahawks",
    optionC: "Green Bay Packers",
    optionD: "San Francisco 49ers",
    correctOption: "b",
    category: "draft_history",
    difficulty: "medium",
  },
  {
    question: "The 'Mr. Irrelevant' award goes to whom?",
    optionA: "The first pick in the draft",
    optionB: "The last pick in the draft",
    optionC: "The best undrafted free agent",
    optionD: "The most traded player",
    correctOption: "b",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "In 2004, Eli Manning refused to play for which team that drafted him #1 overall?",
    optionA: "Cleveland Browns",
    optionB: "Oakland Raiders",
    optionC: "San Diego Chargers",
    optionD: "Arizona Cardinals",
    correctOption: "c",
    category: "draft_history",
    difficulty: "medium",
  },

  // ── BATCH 2: HARD (13 more) ────────────────────────────────────────────────
  {
    question: "Which player holds the record for most bench press reps (225 lbs) at the NFL Combine with 49 reps?",
    optionA: "Stephen Paea",
    optionB: "Justin Ernest",
    optionC: "Mitch Petrus",
    optionD: "Mike Kudla",
    correctOption: "b",
    category: "combine",
    difficulty: "hard",
  },
  {
    question: "In 1983, six quarterbacks were drafted in the first round. Which one went #1 overall?",
    optionA: "Dan Marino",
    optionB: "Jim Kelly",
    optionC: "John Elway",
    optionD: "Todd Blackledge",
    correctOption: "c",
    category: "draft_history",
    difficulty: "hard",
  },
  {
    question: "The 2011 draft trade between the Atlanta Falcons and Cleveland Browns to get Julio Jones cost Atlanta how many draft picks?",
    optionA: "3 picks",
    optionB: "5 picks",
    optionC: "4 picks",
    optionD: "6 picks",
    correctOption: "b",
    category: "trades",
    difficulty: "hard",
  },
  {
    question: "Who was the first player ever selected in an NFL Draft (1936)?",
    optionA: "Jay Berwanger",
    optionB: "Sam Francis",
    optionC: "Riley Smith",
    optionD: "Red Grange",
    correctOption: "a",
    category: "draft_history",
    difficulty: "hard",
  },
  {
    question: "In 2014, which OT ran a 4.65 forty at 6'5\" 306 lbs, one of the fastest ever for an offensive lineman?",
    optionA: "Greg Robinson",
    optionB: "Taylor Lewan",
    optionC: "Zack Martin",
    optionD: "Jake Matthews",
    correctOption: "a",
    category: "combine",
    difficulty: "hard",
  },
  {
    question: "The 'Jimmy Johnson trade value chart' assigns how many points to the #1 overall pick?",
    optionA: "2000",
    optionB: "2500",
    optionC: "3000",
    optionD: "3400",
    correctOption: "c",
    category: "trades",
    difficulty: "hard",
  },
  {
    question: "Which team drafted Tony Romo?",
    optionA: "Dallas Cowboys as a 6th rounder",
    optionB: "He was undrafted",
    optionC: "Green Bay Packers as a 7th rounder",
    optionD: "Dallas Cowboys as a 5th rounder",
    correctOption: "b",
    category: "draft_history",
    difficulty: "hard",
  },
  {
    question: "In the 2000 NFL Draft, Tom Brady was selected with which overall pick number?",
    optionA: "187th",
    optionB: "199th",
    optionC: "201st",
    optionD: "174th",
    correctOption: "b",
    category: "draft_history",
    difficulty: "hard",
  },
  {
    question: "The broad jump at the NFL Combine measures explosive power. What is considered an elite broad jump for a WR?",
    optionA: "9 feet or more",
    optionB: "10 feet or more",
    optionC: "11 feet or more",
    optionD: "12 feet or more",
    correctOption: "c",
    category: "combine",
    difficulty: "hard",
  },
  {
    question: "In 2012, the Minnesota Vikings traded Percy Harvin to the Seattle Seahawks. What round picks did they receive?",
    optionA: "1st and 7th round picks",
    optionB: "1st, 3rd, and 7th round picks",
    optionC: "2nd and 5th round picks",
    optionD: "1st and conditional 3rd round picks",
    correctOption: "a",
    category: "trades",
    difficulty: "hard",
  },
  {
    question: "Which team has never had the #1 overall pick in the NFL Draft?",
    optionA: "Dallas Cowboys",
    optionB: "Green Bay Packers",
    optionC: "Pittsburgh Steelers",
    optionD: "Seattle Seahawks",
    correctOption: "c",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "The shuttle run (short shuttle/5-10-5) at the Combine tests what specific ability?",
    optionA: "Straight-line acceleration",
    optionB: "Lateral quickness and change of direction",
    optionC: "Vertical explosiveness",
    optionD: "Stamina under pressure",
    correctOption: "b",
    category: "combine",
    difficulty: "hard",
  },
  {
    question: "In 1989, the Dallas Cowboys traded Herschel Walker to the Minnesota Vikings in one of the most lopsided trades in NFL history. How many players/picks did Dallas receive?",
    optionA: "5 players and 3 draft picks",
    optionB: "3 players and 6 draft picks",
    optionC: "5 players and 8 draft picks",
    optionD: "2 players and 5 draft picks",
    correctOption: "c",
    category: "trades",
    difficulty: "hard",
  },
];

async function main() {
  console.log("Deleting existing trivia responses...");
  await db.delete(triviaResponses);
  console.log("Deleting existing trivia questions...");
  await db.delete(triviaQuestions);

  console.log(`Inserting ${questions.length} trivia questions...`);
  await db.insert(triviaQuestions).values(questions);

  // Verify
  const rows = await db.select().from(triviaQuestions);
  console.log(`Done. ${rows.length} questions now in database.`);

  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
